#pragma once

#define DISTRHO_PLUGIN_BRAND "Nimble Tools"
#define DISTRHO_PLUGIN_NAME "Misstortion"
#define DISTRHO_PLUGIN_URI "https://nimble.itch.io/misstortion"
#define DISTRHO_PLUGIN_CLAP_ID "tools.nimble.misstortion"

#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_UI_USE_CUSTOM 1
#define DISTRHO_UI_CUSTOM_INCLUDE_PATH "DearImGui.hpp"
#define DISTRHO_UI_CUSTOM_WIDGET_TYPE DGL_NAMESPACE::ImGuiTopLevelWidget
#define DISTRHO_UI_DEFAULT_WIDTH 610
#define DISTRHO_UI_DEFAULT_HEIGHT 180
#define DISTRHO_UI_USER_RESIZABLE 1

#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_NUM_INPUTS 2
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
